config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "home#index"

  resources :events do
    resources :notes, only: [:new, :create, :edit, :update, :destroy]
  end

  namespace :users do
    resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user
  has_many :notes, as: :resource

  def calendar_friendly_start_time
    Date.parse(start_time.to_s).to_s
  end

  def to_param
    [id, name.parameterize].join("-")
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :resource, polymorphic: true

  has_attached_file :attachment
  do_not_validate_attachment_file_type :attachment

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy
  has_many :notes, as: :resource
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new

    # set initial dates
    @event.start_time = start_date
    @event.end_time = start_date
  end

  def edit
    # event
    @event = current_user.events.find(params[:id])
    @event.start_time = @event.start_time.strftime("%d/%m/%Y")
    @event.end_time = @event.end_time.strftime("%d/%m/%Y")

    # notes
    @notes = @event.notes.order(updated_at: :desc)
  end

  def create
    @event = CreateEvent.new(current_user, event_params)
    @event = @event.call

    redirect_to root_url(start_date: @event.calendar_friendly_start_time)

  rescue CreateEvent::NotValidEventException => e
    redirect_to root_url
  end

  def update
    @event = current_user.events.find(params[:id])

    if @event.update_attributes(event_params)
      redirect_to root_url(start_date: @event.calendar_friendly_start_time)
    else
      render "edit"
    end
  end

  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy

    redirect_to root_url(start_date: @event.calendar_friendly_start_time)
  end

  private

  def event_params
    params.require(:event).permit(:name, :start_time, :end_time, :color)
  end

  def start_date
    start_date = params[:start_date] || Date.today.to_s
    Date.parse(start_date).strftime("%d/%m/%Y")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events= current_user.events.where(start_time: safe_month_range)
  end

  private

  # This is so that all events should show on the calendar event if different
  # month
  def safe_month_range
    start_date = params[:start_date] || Date.today.to_s
    date = Date.parse(start_date)

    (date.beginning_of_month-5.days)..(date.end_of_month + 5.days)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  def new
    @event = event
    @note = Note.new
  end

  def edit
    @event = event
    @note = @event.notes.find(params[:id])
  end

  def create
    @note = Note.new(note_params)
    @note.resource = event
    @note.save!

    redirect_to edit_event_url(event)
  end

  def update
    @note = event.notes.find(params[:id])
    @note.update!(note_params)

    redirect_to edit_event_url(event)
  end
  
  def destroy
    @note = Note.find(params[:id])
    @note.destroy!

    redirect_to edit_event_url(event)
  end

  private

  def note_params
    params.require(:note).permit(:content, :attachment)
  end

  def event
    Event.find(params[:event_id])
  end
end

app/controllers/users/notes_controller.rb
class Users::NotesController < ApplicationController

  def index
    @notes = current_user.notes.order(updated_at: :desc)
  end

  def new
    @note = Note.new
  end

  def edit
    @note = current_user.notes.find(params[:id])
  end

  def update
    @note = current_user.notes.find(params[:id])
    @note.update!(note_params)

    redirect_to users_notes_url
  end

  def create
    @note = build_note
    @note.save!

    redirect_to users_notes_url
  end

  def destroy
    @note = current_user.notes.find(params[:id])
    @note.destroy!

    redirect_to users_notes_url
  end

  private

  def note_params
    params.require(:note).permit(:content, :attachment)
  end

  def build_note
    note = Note.new(note_params)
    note.resource = current_user

    note
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_today
    Date.today.to_s
  end

  def popover_events_template(events)
    events.map do |event|
      "<div> #{fa_icon('calendar-o')} #{link_to(event.name, edit_event_path(event))} </div>"
    end.join(" ").html_safe
  end
end

app/views/events/_calendar_event.html.haml
.row
  .col-lg-12
    .event{ style: "background-color: #{event.color}" }
      = link_to event.name, edit_event_path(event), class: "link truncate"

app/views/events/_form.html.haml
.row.form-group
  .col-lg-12
    = f.label :name
    = f.text_field :name, class: "form-control", placeholder: "What is the name of your event?"

.row.form-group
  .col-lg-12
    = f.label :start_time
    %small
      %i (dd/mm/yyyy)

    = f.text_field :start_time, class: "form-control start-time", placeholder: "When will the event start?"

.row.form-group
  .col-lg-12
    = f.label :end_time
    %small
      %i (dd/mm/yyyy)

    = f.text_field :end_time, class: "form-control end-time", placeholder: "When will the event end?"

.row.form-group
  .col-lg-12
    = f.label :color
    = f.text_field :color, class: "form-control colorpicker"

app/views/events/_multiple_events.html.haml
= render "events/calendar_event", event: first_event

.row
  .col-lg-12
    .other-events
      %input{ type: "button", value: "#{events.count} more...", class: "btn btn-link", data: { toggle: "popover", content: "#{popover_events_template(events)}" }, title: "#{date.strftime('%b %d, %Y')}" }

app/views/events/edit.html.haml
.row
  .col-lg-6
    = form_for @event do |f|
      %p.lead.text-center Edit `#{@event.name}`

      = render partial: "form", locals: { f: f }

      .row.form-group.text-center
        .col-lg-12
          = f.submit "Update", class: "btn btn-primary btn-lg"
          = link_to "Delete", event_path(@event), method: :delete, class: "btn btn-danger btn-lg", data: { confirm: "Are you sure you want to remove this event?" }
          = link_to "Cancel", root_path(start_date: @event.calendar_friendly_start_time), class: "btn btn-default btn-lg"

  .col-lg-6
    %p.lead.text-center Notes

    - if @notes.any?

      .bottom10
        .pull-right
          = link_to "create a note", new_event_note_path(@event)
        .clearfix

      - @notes.each do |note|
        = render "notes/note", note: note, edit_url: edit_event_note_path(@event, note), remove_url: event_note_path(@event, note)

    - else
      .row.text-center
        .col-lg-12
          %span
            No records found.

            %u
              = link_to "Create", new_event_note_path(@event)

            one

app/views/events/new.html.haml
.row
  .col-lg-6.col-lg-offset-3
    = form_for @event do |f|
      %p.lead.text-center Create an Event

      = render partial: "form", locals: { f: f }

      .row.form-group.text-center
        .col-lg-12
          = f.submit "Create", class: "btn btn-primary btn-lg"
          = link_to "Cancel", root_path(start_date: @event.start_time), class: "btn btn-default btn-lg"

app/views/home/index.html.haml
.row
  .col-lg-12
    = month_calendar events: @events do |date, events|
      .row
        .col-lg-12

          .row
            .col-lg-12
              .pull-right
                %p
                  = link_to date.day, new_event_path(start_date: date.to_s), class: "link"

              .clearfix

          - if events.any?
            - if events.many? && (event = events.shift)
              = render "events/multiple_events", first_event: event, events: events, date: date
            - else
              = render "events/calendar_event", event: events.first

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= t("app.name")
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag Ckeditor.cdn_url

    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }

  %body
    .container
      .row
        .col-lg-12
          %h2.text-center
            = fa_icon("calendar")
            = t("app.name")
          %hr

      .row
        .col-lg-12
          = yield

app/views/notes/_form.html.haml
= f.cktext_area :content, ckeditor: { enterMode: 2 }

- if f.object.attachment?
  .top10
    %span 
      This note has an existing attachment named
      = link_to f.object.attachment_file_name, f.object.attachment.url

.top10
  = f.file_field :attachment

app/views/notes/_note.html.haml
.row.bottom10
  .col-lg-12
    .well
      %span
        %u
          = fa_icon("clock-o")
          #{note.created_at.strftime("%b %d, %Y %I:%M %P")}

      (
      = link_to "edit", edit_url
      or
      = link_to "remove", remove_url, method: :delete, class: "text-danger", data: { confirm: "Are you sure you want to remove this resource?" }
      )

      - if note.attachment?
        .top10
          %span 
            Attachment:
            = link_to note.attachment_file_name, note.attachment.url


      .top10
        = note.content.html_safe

app/views/notes/edit.html.haml
.row
  .col-lg-6.col-lg-offset-3
    %p.lead.text-center 
      Edit this note

    = form_for [@event, @note], html: { multipart: true } do |f|
      = render "notes/form", f: f

      .top10
        = f.submit "Update this note", class: "btn btn-primary btn-lg"
        = link_to "Cancel", edit_event_path(@event), class: "btn btn-default btn-lg"

app/views/notes/new.html.haml
.row
  .col-lg-6.col-lg-offset-3
    %p.lead.text-center 
      Add a note for your event `#{@event.name}`

    = form_for [@event, @note], html: { multipart: true } do |f|
      = render "notes/form", f: f

      .top10
        = f.submit "Add this note", class: "btn btn-primary btn-lg"
        = link_to "Cancel", edit_event_path(@event), class: "btn btn-default btn-lg"

app/views/simple_calendar/_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    %span.calendar-title
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view

  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block)
                - capture_haml(day, sorted_events.fetch(day, []), &block)
              - else
                - block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_month_calendar.html.haml
.simple-calendar
  .row
    .col-lg-12
      = fa_icon("user-circle")
      = current_user.email
      = link_to "notes(#{current_user.notes.count})", users_notes_path
      = link_to "logout", destroy_user_session_path, method: :delete

  .calendar-heading
    .pull-left
      %p.lead 
        #{t('date.month_names')[start_date.month]} #{start_date.year}

    .pull-right
      = link_to t('simple_calendar.previous', default: 'previous'), calendar.url_for_previous_view
      = link_to "today", root_path(start_date: date_today)
      = link_to t('simple_calendar.next', default: 'next'), calendar.url_for_next_view

    .clearfix

  %table.table.table-bordered.table-responsive
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th
            .pull-right
              %p= t('date.abbr_day_names')[day.wday]

    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block)
                - capture_haml(day, sorted_events.fetch(day, []), &block)
              - else
                - block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_week_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    %span.calendar-title
      Week #{calendar.week_number}
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block)
                - capture_haml(day, sorted_events.fetch(day, []), &block)
              - else
                - block.call day, sorted_events.fetch(day, [])

app/views/users/notes/edit.html.haml
.row
  .col-lg-6.col-lg-offset-3
    %p.lead.text-center 
      Edit this note

    = form_for @note, url: users_note_path, html: { multipart: true } do |f|
      = render "notes/form", f: f

      .top10
        = f.submit "Update this note", class: "btn btn-primary btn-lg"
        = link_to "Cancel", users_notes_path, class: "btn btn-default btn-lg"

app/views/users/notes/index.html.haml
.row
  .col-lg-6.col-lg-offset-3
    %p.lead.text-center Notes

    - if @notes.any?

      .bottom10
        .pull-left
          = link_to "back to calendar", root_path
        .pull-right
          = link_to "create a note", new_users_note_path
        .clearfix

      - @notes.each do |note|
        = render "notes/note", note: note, edit_url: edit_users_note_path(note), remove_url: users_note_path(note)

    - else
      .row.text-center
        .col-lg-12
          %span
            You don't have any notes.

            %u
              = link_to "Create", new_users_note_path

            one or go

            %u
              = link_to "back", root_path

            to calendar.

app/views/users/notes/new.html.haml
.row
  .col-lg-6.col-lg-offset-3
    %p.lead.text-center 
      Add a note

    = form_for @note, url: users_notes_path, html: { multipart: true } do |f|
      = render "notes/form", f: f

      .top10
        = f.submit "Add this note", class: "btn btn-primary btn-lg"
        = link_to "Cancel", users_notes_path, class: "btn btn-default btn-lg"